### ISSUE TITLE
Need some help using the example

### ISSUE THREAD

**Issue by sharived** [jbx-protocol/juice-sdk#1]
I'm pretty new to all this and having some basic issues.

I installed using 
  npm install juice-sdk
   npm install --save ethers

Put the example in a file called balance.ts and ran

tsc init 
tsc balance.ts
node balance.js

and I get the following error
...node_modules/juice-sdk/dist/index.js:1
import { Contract } from "@ethersproject/contracts";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/sharivedovato/firebase-apps/public/balance.js:43:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Note that I'm doing this as a first step.  Am actually trying to use from my index.html like:
    <script>var exports = {};</script>
   <script  src = "scripts/require.js"></script>
  <script  src="balance.js">

my issue here is
 balance.js:46 Uncaught TypeError: providers_1.JsonRpcProvider is not a constructor
    at balance.js:46:16

Also note that I had to modify the .js file and put in [] in require
var ethers = require(['ethers']).ethers;
var providers_1 = require(["@ethersproject/providers"]);
var juice_sdk_1 = require(["juice-sdk"]);
// 1. Create your JSON RPC provider with ethers.js
var RPC_HOST = "https://mainnet.infura.io/v3/86b4af9ed0704e3fbd8bed72eaca2805";
var provider = new providers_1.JsonRpcProvider(RPC_HOST);  <--- this is line it's complaining about

**Comment by aeolianeth** [comment]
@sharived happy to help!

I think your problem might be with your `tsconfig.json`. Here is an example one that I managed to get working:

```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true
  }
}
```

Also, I just updated the `juice-sdk` package with a small fix: the latest version is `0.0.5-alpha`.

Let me know how you go with that 🙏

**Comment by sharived** [comment]
Thanks.  Still no luck.  I matched your tsconfig.json and updated to the latest version of juice-sdk.  How are you testing it, perhaps I can try to recreate what you are doing.  Note that I do get an error when installing juice-sdk - perhaps I need to downgrade my version of node.

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hardhat@2.9.5',
npm WARN EBADENGINE   required: { node: '^12.0.0 || ^14.0.0 || ^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.0.0', npm: '8.6.0' }
npm WARN EBADENGINE }
npm WARN deprecated testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
npm WARN deprecated @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts

**Comment by aeolianeth** [comment]
@sharived ah - I missed something 😅 . It looks like you're trying to run your `balance` script in a node.js environment.

I've updated the package to `0.0.6-alpha`, and also added an `examples/` directory which includes a working typescript/node example.

Also see https://github.com/jbx-protocol/juice-tools/tree/main/embed/project/balance for an in-browser example that uses Vite as its bundler

**Comment by aeolianeth** [comment]
@sharived - I've found a better solution 😄 will report back soon.

**Comment by aeolianeth** [comment]
@sharived this library now supports both node.js and browser environments 🥳.

Please take another look at the typescript-node example in `examples/` and let me know if you have any luck.

**Comment by sharived** [comment]
Thanks!  So I can run the typescript-node balance example now - however I'm not understanding the result.  For the default project ID 2, I get
BigNumber { _hex: '0x08ae38ef9b01c000', _isBigNumber: true }
Not sure what number this relates to.  Also I'm guessing this is for V2?  If I put in a V1.1 ID (like mine 642) I get an error "INVALID_ARGUMENT"

Is there something equivalent for V1.1?  Wondering if we should switch to V2 since we haven't really gone live yet.

My goal is to get the embed version working - but will likely have the same version ID issue as above.  But right now where I'm at is - 
1.  Seemed to need to use a .js version of main (so ran tsc first)
2. Complained about exports so I added <script>var exports = {};</script>
3. Issue with require - which I'm still stuck on.  Tried npm install requirejs and then loaded script, but then it wants me to change all of the requires in the js files to []
require.js:168 Uncaught Error: Module name "style.css" has not been loaded yet for context: _. Use require([])
https://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:168:17)
    at Object.localRequire [as require] (require.js:1436:44)
    at requirejs (require.js:1797:24)
    at main.js:39:1

BTW I use firebase to deploy

**Comment by aeolianeth** [comment]
@sharived nice!! A positive step 👣 

> For the default project ID 2, I get
> BigNumber { _hex: '0x08ae38ef9b01c000', _isBigNumber: true }

This is great! All you'll need to do is call `.toString()` to get the balance in wei: https://docs.ethers.io/v5/api/utils/bignumber/

```js
balance.toString() // outputs BigNumber as a human-readable number, using 10e18 decimals (wei)
```

An alternative is to use the `ethers` library utility function called `formatEther`

```js
import { formatEther } from "ethers"

console.log(formatEther(balance)) //  will output the balance in ETH
```

This package does only currently support Juicebox V2. I can probably get you a V1.1 equivalent of this package though 🙏 .

You are more than welcome to re-launch your Juicebox project on Juicebox V2. You currently can't migrate your V1 project to V2 yet, but we're actively working on a solution to this: https://github.com/jbx-protocol/juice-interface/issues/1056.

**Comment by aeolianeth** [comment]
Hey @sharived ! Anything more I can help with here?

**Comment by sharived** [comment]
Thanks!  I’m good for now.  We might still need to switch to V2.
